//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_ctrl
    {
        public int id { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public System.DateTime created { get; set; }
        public string username { get; set; }
        public string url { get; set; }
        public string referrer { get; set; }
        public System.Guid guid { get; set; }
    }
}
