//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_comments
    {
        public int id { get; set; }
        public string username { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string itemID { get; set; }
        public string type { get; set; }
        public string audio { get; set; }
    }
}
