//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_favorites
    {
        public int id { get; set; }
        public int itemID { get; set; }
        public string appName { get; set; }
        public System.DateTime created { get; set; }
        public System.Guid userGuid { get; set; }
    }
}
