//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_menu
    {
        public as_menu()
        {
            this.as_menu1 = new HashSet<as_menu>();
            this.as_menuRoles = new HashSet<as_menuRoles>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string pattern { get; set; }
        public Nullable<int> parentID { get; set; }
        public string title { get; set; }
        public string cssclass { get; set; }
    
        public virtual ICollection<as_menu> as_menu1 { get; set; }
        public virtual as_menu as_menu2 { get; set; }
        public virtual ICollection<as_menuRoles> as_menuRoles { get; set; }
    }
}
