//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_mt_metricTypes
    {
        public as_mt_metricTypes()
        {
            this.as_mt_metrics = new HashSet<as_mt_metrics>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> ord { get; set; }
    
        public virtual ICollection<as_mt_metrics> as_mt_metrics { get; set; }
    }
}
