//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_profileMenu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string href { get; set; }
        public string cssClass { get; set; }
        public Nullable<System.Guid> userGuid { get; set; }
    }
}
