//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_settings
    {
        public as_settings()
        {
            this.as_settingAvailableValues = new HashSet<as_settingAvailableValues>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string value { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> typeID { get; set; }
        public string value2 { get; set; }
        public string name { get; set; }
    
        public virtual as_dataTypes as_dataTypes { get; set; }
        public virtual ICollection<as_settingAvailableValues> as_settingAvailableValues { get; set; }
        public virtual as_settingCategories as_settingCategories { get; set; }
    }
}
