//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_sqlGet
    {
        public as_sqlGet()
        {
            this.as_sqlRole = new HashSet<as_sqlRole>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string sql { get; set; }
        public string users { get; set; }
    
        public virtual ICollection<as_sqlRole> as_sqlRole { get; set; }
    }
}
