//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_sqlRole
    {
        public int id { get; set; }
        public int sqlID { get; set; }
        public string role { get; set; }
    
        public virtual as_sqlGet as_sqlGet { get; set; }
    }
}
