//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_settingCategories
    {
        public as_settingCategories()
        {
            this.as_settings = new HashSet<as_settings>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> ord { get; set; }
    
        public virtual ICollection<as_settings> as_settings { get; set; }
    }
}
