//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_textMistakes
    {
        public int id { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public string selectText { get; set; }
        public string url { get; set; }
        public string comment { get; set; }
        public bool correct { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
