//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_userChecks
    {
        public int id { get; set; }
        public string username { get; set; }
        public bool isClosed { get; set; }
        public string note { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public int itemID { get; set; }
    
        public virtual as_userCheckItems as_userCheckItems { get; set; }
    }
}
