//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calc_parameters
    {
        public int id { get; set; }
        public Nullable<int> calcID { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string tooltip { get; set; }
        public Nullable<int> datatypeID { get; set; }
        public string defaultValue { get; set; }
    
        public virtual as_dataTypes as_dataTypes { get; set; }
        public virtual calc_calcs calc_calcs { get; set; }
    }
}
