//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_listInstances
    {
        public cl_listInstances()
        {
            this.cl_listInstanceItems = new HashSet<cl_listInstanceItems>();
        }
    
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public string createdBy { get; set; }
        public int itemID { get; set; }
        public int listID { get; set; }
        public string roles { get; set; }
        public string users { get; set; }
    
        public virtual ICollection<cl_listInstanceItems> cl_listInstanceItems { get; set; }
        public virtual cl_lists cl_lists { get; set; }
    }
}
