//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_listInstanceItems
    {
        public int id { get; set; }
        public System.DateTime modified { get; set; }
        public string modifiedBy { get; set; }
        public int listInstanceID { get; set; }
        public int listItemID { get; set; }
        public string value { get; set; }
        public bool isGood { get; set; }
    
        public virtual cl_listInstances cl_listInstances { get; set; }
        public virtual cl_listItems cl_listItems { get; set; }
    }
}
