//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_orderItems
    {
        public int id { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual crm_orders crm_orders { get; set; }
        public virtual ct_products ct_products { get; set; }
    }
}
