//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_docTypes
    {
        public doc_docTypes()
        {
            this.doc_docTypeTemplates = new HashSet<doc_docTypeTemplates>();
            this.doc_docs = new HashSet<doc_docs>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<doc_docTypeTemplates> doc_docTypeTemplates { get; set; }
        public virtual ICollection<doc_docs> doc_docs { get; set; }
    }
}
