//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fedchenko_docStatus
    {
        public fedchenko_docStatus()
        {
            this.fedchenko_documents = new HashSet<fedchenko_documents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<fedchenko_documents> fedchenko_documents { get; set; }
    }
}
