//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fedchenko_invoiceStatus
    {
        public fedchenko_invoiceStatus()
        {
            this.fedchenko_invoices = new HashSet<fedchenko_invoices>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<fedchenko_invoices> fedchenko_invoices { get; set; }
    }
}
