//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fedchenko_mail
    {
        public int Id { get; set; }
        public Nullable<int> MailStatus { get; set; }
        public System.DateTime Date { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Description { get; set; }
        public string SendingSystem { get; set; }
        public string TrackNumber { get; set; }
        public string TrackNumberBack { get; set; }
        public System.DateTime DateBack { get; set; }
    
        public virtual fedchenko_mailStatus fedchenko_mailStatus { get; set; }
    }
}
