//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gurevskiy_invoiceStatuses
    {
        public gurevskiy_invoiceStatuses()
        {
            this.gurevskiy_invoices = new HashSet<gurevskiy_invoices>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<gurevskiy_invoices> gurevskiy_invoices { get; set; }
    }
}
