//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gurevskiy_contracts
    {
        public int id { get; set; }
        public int typeID { get; set; }
        public int statusID { get; set; }
        public int partnerID { get; set; }
        public System.DateTime date { get; set; }
        public string number { get; set; }
        public Nullable<decimal> sum { get; set; }
        public string comment { get; set; }
        public string link { get; set; }
    
        public virtual gurevskiy_contractStatuses gurevskiy_contractStatuses { get; set; }
        public virtual gurevskiy_contractTypes gurevskiy_contractTypes { get; set; }
        public virtual gurevskiy_partner gurevskiy_partner { get; set; }
    }
}
