//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gurevskiy_contractStatuses
    {
        public gurevskiy_contractStatuses()
        {
            this.gurevskiy_contracts = new HashSet<gurevskiy_contracts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<gurevskiy_contracts> gurevskiy_contracts { get; set; }
    }
}
