//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_humanSpecializations
    {
        public int id { get; set; }
        public Nullable<int> humanID { get; set; }
        public Nullable<int> specializationID { get; set; }
    
        public virtual hr_humans hr_humans { get; set; }
        public virtual hr_specializations hr_specializations { get; set; }
    }
}
