//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class imp_items
    {
        public imp_items()
        {
            this.imp_itemLog = new HashSet<imp_itemLog>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string datatable { get; set; }
        public string sqlInsert { get; set; }
        public string sqlUpdate { get; set; }
        public string sqlDelete { get; set; }
    
        public virtual ICollection<imp_itemLog> imp_itemLog { get; set; }
    }
}
