//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mikhailova_invoices
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string number { get; set; }
        public int contagentID { get; set; }
        public string desc { get; set; }
        public int statusID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Mikhailova_contagents Mikhailova_contagents { get; set; }
        public virtual Mikhailova_statuses_invoces Mikhailova_statuses_invoces { get; set; }
    }
}
