//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mikhailova_contagents
    {
        public Mikhailova_contagents()
        {
            this.Mikhailova_contracts = new HashSet<Mikhailova_contracts>();
            this.Mikhailova_invoices = new HashSet<Mikhailova_invoices>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Mikhailova_contracts> Mikhailova_contracts { get; set; }
        public virtual ICollection<Mikhailova_invoices> Mikhailova_invoices { get; set; }
        public virtual Mikhailova_contagents Mikhailova_contagents1 { get; set; }
        public virtual Mikhailova_contagents Mikhailova_contagents2 { get; set; }
    }
}
