//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mikhailova_docTypes
    {
        public Mikhailova_docTypes()
        {
            this.Mikhailova_contracts = new HashSet<Mikhailova_contracts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<Mikhailova_contracts> Mikhailova_contracts { get; set; }
    }
}
