//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class molchanov_invoiceStatuses
    {
        public molchanov_invoiceStatuses()
        {
            this.molchanov_invoices = new HashSet<molchanov_invoices>();
            this.molchanov_logInvoiceStatuses = new HashSet<molchanov_logInvoiceStatuses>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<molchanov_invoices> molchanov_invoices { get; set; }
        public virtual ICollection<molchanov_logInvoiceStatuses> molchanov_logInvoiceStatuses { get; set; }
    }
}
