//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class molchanov_logDocStatuses
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string notice { get; set; }
        public string userName { get; set; }
        public int docStatusID { get; set; }
    
        public virtual molchanov_docStatuses molchanov_docStatuses { get; set; }
    }
}
