//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class motskin_sendSystems
    {
        public motskin_sendSystems()
        {
            this.motskin_mails = new HashSet<motskin_mails>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<motskin_mails> motskin_mails { get; set; }
    }
}
