//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class motskin_documentTypes
    {
        public motskin_documentTypes()
        {
            this.motskin_documents = new HashSet<motskin_documents>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<motskin_documents> motskin_documents { get; set; }
    }
}
