//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class motskin_invoiceStatuses
    {
        public motskin_invoiceStatuses()
        {
            this.motskin_invoices = new HashSet<motskin_invoices>();
            this.motskin_invoiceStatusLog = new HashSet<motskin_invoiceStatusLog>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<motskin_invoices> motskin_invoices { get; set; }
        public virtual ICollection<motskin_invoiceStatusLog> motskin_invoiceStatusLog { get; set; }
    }
}
