//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdv_mails
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<int> contractorFromID { get; set; }
        public Nullable<int> contractorToID { get; set; }
        public string description { get; set; }
        public Nullable<int> deliveryServiceID { get; set; }
        public Nullable<int> trackNumber { get; set; }
        public Nullable<int> deleveryStatusID { get; set; }
        public Nullable<int> reTrackNumber { get; set; }
        public Nullable<System.DateTime> reDateOfReceiving { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual pdv_contractors pdv_contractors { get; set; }
        public virtual pdv_contractors pdv_contractors1 { get; set; }
        public virtual pdv_deliveryService pdv_deliveryService { get; set; }
        public virtual pdv_deliveryMailStatuses pdv_deliveryMailStatuses { get; set; }
    }
}
