//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdv_invoices
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> contractorID { get; set; }
        public string comment { get; set; }
        public Nullable<int> invoiceStatusID { get; set; }
        public Nullable<int> documentID { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual pdv_contractors pdv_contractors { get; set; }
        public virtual pdv_invoiceStatuses pdv_invoiceStatuses { get; set; }
        public virtual pdv_documents pdv_documents { get; set; }
    }
}
