//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class proc_processItems
    {
        public int id { get; set; }
        public int processID { get; set; }
        public int ord { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string roles { get; set; }
        public string users { get; set; }
        public bool isFinish { get; set; }
        public string color { get; set; }
    
        public virtual proc_processes proc_processes { get; set; }
    }
}
