//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class proc_processes
    {
        public proc_processes()
        {
            this.proc_processItems = new HashSet<proc_processItems>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<proc_processItems> proc_processItems { get; set; }
    }
}
