//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_statuses
    {
        public ps_statuses()
        {
            this.ps_partners = new HashSet<ps_partners>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string color { get; set; }
        public string order { get; set; }
    
        public virtual ICollection<ps_partners> ps_partners { get; set; }
    }
}
