//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rosh_sqlQueriesTable
    {
        public int id { get; set; }
        public string con { get; set; }
        public string manager { get; set; }
        public int timeLimit { get; set; }
        public int rowsLimit { get; set; }
    }
}
