//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rosh_docTypes
    {
        public rosh_docTypes()
        {
            this.rosh_docTypes1 = new HashSet<rosh_docTypes>();
            this.rosh_documents = new HashSet<rosh_documents>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> parentID { get; set; }
    
        public virtual ICollection<rosh_docTypes> rosh_docTypes1 { get; set; }
        public virtual rosh_docTypes rosh_docTypes2 { get; set; }
        public virtual ICollection<rosh_documents> rosh_documents { get; set; }
    }
}
