//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rosh_contragents
    {
        public rosh_contragents()
        {
            this.rosh_documents = new HashSet<rosh_documents>();
            this.rosh_orders = new HashSet<rosh_orders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public int sourceID { get; set; }
        public int contragentStatusID { get; set; }
        public bool needActive { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> nextContact { get; set; }
    
        public virtual rosh_contragentSources rosh_contragentSources { get; set; }
        public virtual rosh_contragentStatuses rosh_contragentStatuses { get; set; }
        public virtual ICollection<rosh_documents> rosh_documents { get; set; }
        public virtual ICollection<rosh_orders> rosh_orders { get; set; }
    }
}
