//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsilurik_contractors
    {
        public tsilurik_contractors()
        {
            this.tsilurik_documents = new HashSet<tsilurik_documents>();
            this.tsilurik_invoices = new HashSet<tsilurik_invoices>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tsilurik_documents> tsilurik_documents { get; set; }
        public virtual ICollection<tsilurik_invoices> tsilurik_invoices { get; set; }
    }
}
