//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tst_cars
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<int> driverID { get; set; }
    
        public virtual tst_drivers tst_drivers { get; set; }
    }
}
