//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_projects
    {
        public tt_projects()
        {
            this.fin_finances = new HashSet<fin_finances>();
            this.recl_items = new HashSet<recl_items>();
            this.doc_docs = new HashSet<doc_docs>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<fin_finances> fin_finances { get; set; }
        public virtual ICollection<recl_items> recl_items { get; set; }
        public virtual ICollection<doc_docs> doc_docs { get; set; }
    }
}
