//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class udovika_statusEmail
    {
        public udovika_statusEmail()
        {
            this.udovika_email = new HashSet<udovika_email>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<udovika_email> udovika_email { get; set; }
    }
}
