//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class udovika_invoice
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string number { get; set; }
        public int contractorID { get; set; }
        public string note { get; set; }
        public int statusID { get; set; }
    
        public virtual udovika_contractor udovika_contractor { get; set; }
        public virtual udovika_statusInvoice udovika_statusInvoice { get; set; }
    }
}
