//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vas_documents
    {
        public int id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public System.DateTime date { get; set; }
        public decimal sum { get; set; }
        public string link { get; set; }
        public int typeID { get; set; }
        public int statusID { get; set; }
        public int contractorID { get; set; }
        public string comment { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string code { get; set; }
    
        public virtual vas_contractors vas_contractors { get; set; }
        public virtual vas_docStatuses vas_docStatuses { get; set; }
        public virtual vas_docTypes vas_docTypes { get; set; }
    }
}
