//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vas_mails
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string comment { get; set; }
        public string mailSystem { get; set; }
        public string trackNumber { get; set; }
        public string trackNumberRepay { get; set; }
        public Nullable<System.DateTime> dateReplay { get; set; }
        public int statusID { get; set; }
        public string code { get; set; }
    
        public virtual vas_mailStatuses vas_mailStatuses { get; set; }
    }
}
